- Active Services:
    - Blog:
        href: http://blog.thanh0x.com/
        description: WordPress blog
        icon: sh-wordpress

    - Udemy Coupons Server:
        href: https://coupons.thanh0x.com/
        description: 100% OFF Udemy coupon service
        icon: si-udemy  # No sh-udemy available

    - Petking 5 Blog:
        href: https://petking5.thanh0x.com/
        description: The main blog for reverse engineering game Petking 5
        icon: sh-ghost

- Internal Services:
    - Public Dev Test:
        href: https://public.thanh0x.com/
        description: Expose dev test environment to public
        icon: mdi-code-tags  # No sh-code-tags available

    - Nextcloud:
        href: https://cloud.thanh0x.com/
        description: Cloud storage (backup and sync)
        icon: sh-nextcloud

    - Gitea:
        href: https://gitea.thanh0x.com/huythanh0x
        description: Git hosting (store tons of repo that cannot be on GitHub)
        icon: sh-gitea

- Private Services:
    - Cloudflare:
        description: Private Service (no public access)
        icon: sh-cloudflare

    - NginxProxy Manager:
        description: Private Service (no public access)
        icon: sh-nginx

    - Tailscale VPN:
        description: Private Service (no public access)
        icon: sh-tailscale

# Deactivated services grouped at the bottom for informational purposes only, with no accessibility
- Inactive Services:
    #<!-- initiallyCollapsed: true -->
    - Trilium:
        description: Note - Switched to local Obsidian with sync with Github plugin
        icon: sh-notion

    - XBackbone:
        description: Image back up - Switched to NextCloud sync and Github storage
        icon: mdi-folder  # No sh-folder available

    - Linkwarden:
        description: Read later - Switched to built-in feature of Safari + Raindrop.io
        icon: mdi-link-variant  # No sh-linkwarden available

    - Traggo:
        description: Switched to use Timery for time tracking [Apple Ecosystem]
        icon: mdi-timer  # No sh-timer available

    - Udemy Coupons Test Server:
        description: Skipped dev env, just push to prod
        icon: si-udemy  # No sh-udemy available

    - DBO Game Server:
        description: Switched to play Pokemon Legends Arceus
        icon: mdi-gamepad-variant  # No sh-gamepad available

    - Kasm:
        description: Working from home so won’t need it anymore
        icon: mdi-desktop-mac  # No sh-kasm available

    - BookStack:
        description: Obsidian is btter for knowlge management
        icon: sh-bookstack

    - VSCode:
        description: Working from home so won’t need it anymore
        icon: mdi-microsoft-visual-studio-code  # No sh-vscode available

    - AppFlowy:
        description: Have no task management system for now
        icon: sh-appflowy

    - Archivebox:
        href: https://archive.thanh0x.com/public/
        description: Archiving service - I have no use of this anymore
        icon: mdi-archive  # No sh-archive available

    - Wallabag:
        href: https://wallabag.thanh0x.com/
        description: Bookmarking service - Built-in Safari feature and Raindrop.io are much better
        icon: sh-wallabag

- Reading:
    - Medium:
        href: https://medium.com/
        icon: si-medium  # No sh-medium available

    - Github starred list:
        href: https://github.com/Huythanh0x?tab=stars
        icon: mdi-github  # No sh-github available